import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { fetchApi } from "@/api/fetchApi";
import Main from "@/components/homePageComponents/Main";


export default function Home({ allCountriesDetails }) {
  return (
    <>
      <Head>
        <title>country searcher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"min-h-screen bg-LightBackground  font-Nunito"}>
        <Main allCountriesDetails={allCountriesDetails}/>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const allCountriesDetails = await fetchApi(`${process.env.ENV_BASEURL}/all`);
  return {
    props: {
      allCountriesDetails,
    },
  };
}
